services:
  dhiman-html2pdf:
    build: .
    container_name: dhiman-html2pdf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '1'
        reservations:
          memory: 50M
    networks:
      - minhazul-net

networks:
  minhazul-net:
    external: true
 